### ISSUE TITLE
Dropbox data object methods (Tohya, Isaac)

### ISSUE THREAD

**Issue by theflickerman404** [Toyakki/JSIT#75]
the drop box data access object does not currently support the following methods:
- saveUser
- getFiles
- getUserByEmail
- userExistsByEmail
- getAllUsers

as indicated in the project group chat, I recommend storing all user emails and other information as a text file in some format and accessing that to load the necessary data to implement the above methods

**Comment by Toyakki** [comment]
Finished saveUser, getFiles, and userExistsByEmail methods. Their tests worked well.

**Comment by Toyakki** [comment]
I also finished the getUserByEmail method. The dropbox test worked well.

**Comment by Toyakki** [comment]
The folder structure would look like the following in the dropbox.
/
├── CSC207/
│   ├── henrik-ibsen707@gmail.com/
│   │   ├── info.txt
│   │   ├── Assignment1.pdf
│   │   └── Assignment2.pdf
│   ├── student2@example.com/
│   │   ├── info.txt
│   │   ├── Assignment1_Submission.pdf
│   │   └── Assignment2_Submission.pdf
│   └── instructor@example.com/
│       └── info.txt
├── STA257/
│   ├── henrik-ibsen707@gmail.com/
│   │   ├── info.txt
│   │   
│   └── student1@example.com/
│       └── info.txt

**Comment by Toyakki** [comment]
I'm not sure what you want to return in getAllUsers, so I leave it for the moment.
